defaults:
  - default.yaml

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/accuracy" # name of the logged metric which determines when model is improving
  mode: "max" # "max" means higher metric value is better, can be also "min"
  patience: 5 # how many validation epochs of not improving until training stops
  min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement
